// <auto-generated />
using CoreIntroNC19.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreIntroNC19.Migrations
{
    [DbContext(typeof(CoreIntroNC19Context))]
    [Migration("20191204134557_AddSeed")]
    partial class AddSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoreIntroNC19.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Person");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Name = "Kalle",
                            Salary = 20000
                        },
                        new
                        {
                            Id = 2,
                            Age = 45,
                            Name = "Anna",
                            Salary = 15000
                        },
                        new
                        {
                            Id = 3,
                            Age = 62,
                            Name = "Nisse",
                            Salary = 65000
                        },
                        new
                        {
                            Id = 4,
                            Age = 23,
                            Name = "Pelle",
                            Salary = 10000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
